services:
  juice:
    image: bkimminich/juice-shop:v19.0.0
    ports: ["3006:3000"]
    user: "10001:10001"
    read_only: true
    tmpfs: ["/tmp"]
    security_opt:
      - no-new-privileges:true
    cap_drop: ["ALL"]

